config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :planets do
    resources :bookings, only: [:create, :new]
  end
  resources :bookings, only: [:index, :destroy]
  patch "bookings/:id", to: "bookings#status!", as: :status_booking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :planet
  belongs_to :user

  validates :planet, presence: true
  validates :user, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :number_of_guests, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :status, inclusion: { in: %w(accepted pending rejected) }
end

app/models/planet.rb
class Planet < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos
  geocoded_by :address

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :number_guests, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true
  validates :address, presence: true
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :planets, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :username, :description])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_planet, only: [:new, :create]
  before_action :set_booking, only: [:destroy, :status!]

  def index
    if params[:query] == 'sent'
      @bookings = Booking.where("user_id = ?", current_user)
    else
      @bookings = current_user.planets.map { |planet| planet.bookings }.flatten
    end
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.planet = @planet
    @booking.user = current_user
    if @booking.save
      redirect_to planet_path(@planet)
    else
      render "new"
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, notice: 'Your booking has been deleted successfully.'
  end

  def status!
    if params[:query] == 'accepted'
      @booking.update(status: 'accepted')
    else
      @booking.update(status: 'rejected')
    end
    redirect_to bookings_path
  end

  private

  def set_planet
    @planet = Planet.find(params[:planet_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:user_id, :start_date, :end_date, :number_of_guests)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @planets = Planet.all.sort_by { |planet| planet.bookings.size }.take(5)
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query] == "my_planets"
      @planets = Planet.where("user_id = ?", current_user)
    elsif  params[:query].present?
      sql_query = "name ILIKE :query OR address ILIKE :query"
      @planets = Planet.where(sql_query, query: "%#{params[:query]}%")
    else
      @planets = Planet.all
    end
    @markers = @planets.geocoded.map do |planet|
      {
        lat: planet.latitude,
        lng: planet.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { planet: planet })
      }
    end
  end

  def show
  end

  def new
    @planet = Planet.new
  end

  def edit
  end

  def create
    @planet = Planet.new(planet_params)
    @planet.user = current_user
    if @planet.save
      redirect_to planet_path(@planet)
    else
      render :new
    end
  end

  def update
    if @planet.update(planet_params)
      redirect_to planet_path(@planet), notice: 'Planet is updated'
    else
      render :edit
    end
  end

  def destroy
    @planet.destroy
    redirect_to planets_path, notice: 'Your planet has been deleted successfully.'
  end

  private

  def planet_params
    params.require(:planet).permit(:name, :description, :address, :price, :number_guests, photos: [])
  end

  def set_planet
    @planet = Planet.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="background-black">
  <div class="request">
    <% if params[:query] == 'sent' %>
      <h1> Your Requests Sent </h1>
    <% else  %>
      <h1> Your Requests Received </h1>
    <% end %>
  </div>

  <div class="bookings">
    <% if @bookings.any? %>
      <table>
        <tr>
          <th>Planet</th>
          <th>Number of Guests</th>
          <th>Check-in</th>
          <th>Check-out</th>
          <th>Status</th>

          <% if params[:query] == 'sent' %>
            <th>To</th>
          <% else  %>
            <th>By</th>
            <th>Your Decision?</th>
          <% end %>

          <% if current_user == @bookings.first.user %>
            <th>Delete</th>
          <% end %>
        </tr>

        <% @bookings.each do |booking| %>
          <tr>
            <td> <%= link_to booking.planet.name, planet_path(booking.planet) %> </td>
            <td><%= booking.number_of_guests %> </td>
            <td><%= booking.start_date %></td>
            <td><%= booking.end_date %></td>
            <td><%= booking.status.upcase %></td>

            <% if params[:query] == 'sent' %>
              <td><%= link_to booking.planet.user.username, user_path(booking.planet.user) %></td>
            <% else  %>
              <td><%= link_to booking.user.username, user_path(booking.user) %></td>
              <td> <%= link_to "Accept", status_booking_path(booking, query: 'accepted'), method: :patch if booking.status == 'pending'%> /
                   <%= link_to "Refuse", status_booking_path(booking, query: 'refused'), data: { confirm: "Are you sure?" }, method: :patch if booking.status == 'pending'%>
              </td>
            <% end %>

            <% if current_user == booking.user %>
              <td><%= link_to 'Cancel this booking', booking_path(booking), data: { confirm: "Are you sure?" }, :method => :delete %></td>
            <% end %>
          </tr>
          <% end %>

      </table>

    <% else %>
        <h5 class="no-booking">You currently have no bookings!</h5>
    <% end %>
  </div>

  <div class="centered-btn">
    <%= link_to "Back", root_path, class:"btn btn-outline-warning btn-back" %>
  </div>

</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <%= simple_form_for [@planet, @booking] do |f| %>
      <%= f.input :start_date, as: :date %>
      <%= f.input :end_date, as: :date %>
      <%= f.input :number_of_guests, as: :numeric, min_max: true, input_html: { step: 10 } %>
      <%= f.button :submit, class: "btn-primary" %>
      <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentaPlanet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'shared/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
   <div class="text-banner">
      <h1>Welcome to Rental Planet</h1>
      <p>The luxury space vacation rentals</p>
   </div>
   <div>
     <%= link_to 'Explore worlds nearby', planets_path, type:"button", class:"rental-planet-main-btn btn"%>
   </div>
</div>

<h2>Best Planets</h2>
<div class="container-best-planets">
  <% @planets.each do |planet| %>
  <div class="cards-best-planets">
    <% if planet.photos.attached? %>
      <%= cl_image_tag planet.photos.first.key, height: 200, width: 200, crop: :fill %>
    <% else %>
      <%= image_tag('earth.jpg', height: 200, width: 200) %>
    <% end %>
    <div class="cards-planet-infos">
      <h3><%= link_to planet.name, planet_path(planet) %></h3>
      <p><%= planet.address %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/planets/_info_window.html.erb
<div class="container">
  <div class="card-body">
  	<h2>Name: <%= planet.name %></h2>
    <h3>Price: <%= planet.price %> €</h3>
    <p>Address: <%= planet.address %></p>
  </div>
</div>

app/views/planets/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <%= simple_form_for @planet do |f| %>
        <%= f.input :name %>
        <%= f.input :address, label: 'Address of the nearest Space Station'  %>
        <%= f.input :price, min_max: true, input_html: { step: 1000 } %>
        <%= f.input :number_guests, min_max: true, input_html: { step: 10 } %>
        <%= f.input :description %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.button :submit, class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/planets/index.html.erb
<div class="container-index">
  <br>
  <h1>All planets</h1>
  <br>
  <div class="form-inline">
    <%= form_tag planets_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "To infinite and beyond..."
      %>
      <%= submit_tag "Search", class: "btn btn-outline-warning btn-search" %>
    <% end %>
  </div>

  <div class="container-planets">
    <% @planets.each do |planet| %>
    <div class="card-planet-index" data-aos="fade-right" data-aos-duration="1000">

      <% if planet.photos.attached? %>
        <%= cl_image_tag planet.photos.first.key, height: 200, width: 200, crop: :fill %>
      <% else %>
        <%= image_tag('earth.jpg', height: 200, width: 200) %>
      <% end %>
      <div class="card-planet-infos">
        <br>
        <h2><%= link_to planet.name, planet_path(planet) %></h2>
        <h3><%= planet.address %></h3>
        <p><%= planet.description %></p>
        <br>
        <h2 class="card-planet-price"><%= planet.price %> €</h2>
        <br>
      <br>
      </div>
    </div>
    <% end %>
  </div>

  <div class="map-index">
    <div id="map"
       style="width: 75%; height: 500px;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/planets/new.html.erb
<div class="container">
  <%= simple_form_for @planet do |f| %>
    <%= f.input :name %>
    <%= f.input :address, label: 'Address of the nearest Space Station' %>
    <%= f.input :price, min_max: true, input_html: { step: 1000 } %>
    <%= f.input :number_guests, min_max: true, input_html: { step: 10 } %>
    <%= f.input :description %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.button :submit, class:"btn btn-primary" %>
    <%= link_to 'Cancel', planets_path, class: "btn btn-outline-secondary" %>
  <% end %>
</div>

app/views/planets/show.html.erb
<div class="container-index">
  <div class="carousel-container">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
      <ol class="carousel-indicators">
      <% @planet.photos.each.with_index(0) do |post, index| %>
          <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= index.zero? ? 'active' : '' %>"></li>
        <% end %>
      </ol>
      <div class="carousel-inner">
        <% @planet.photos.each.with_index(0) do |photo, index| %>
          <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
            <%= link_to photo do %>
              <%= image_tag(photo, class: 'd-block w-100 img-fluid') %>
            <% end %>
          </div>
        <% end %>
      </div>


      
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </a>
    </div>
  </div>

  <section id="Services">
    <div class="container-show">
      <div class="card-show">
        <div class="circle-show">
          <h2 class="card-header">Entire planet</h2>
        </div>
        <div class="content-show">
          <p class="text-show">You can have <strong> <%= @planet.name %></strong>  only for yourself or to share it with your friends</p>
        </div>
      </div>
        <div class="card-show">
          <div class="circle-show">
            <h2 class="card-header">Where</h2>
          </div>
          <div class="content-show">
            <p class="text-show">The departing station will be in the city of <strong> <%= @planet.address %></strong> </p>
          </div>
      </div>
        <div class="card-show">
          <div class="circle-show">
            <h2 class="card-header">Capacity and price</h2>
          </div>
          <div class="content-show">
            <p class="text-show">This planet can acccomodate up to <strong> <%= @planet.number_guests %></strong>  guests and will cost <strong><%= @planet.price %> €</strong> per day</p>
          </div>
        </div>

        <% unless current_user == @planet.user  %>
          <div class="btn-container">
        <%= link_to "Make a booking", new_planet_booking_path(@planet), class: "btn-change-border" %>
          </div> 
        <% end %>
        <% if current_user == @planet.user %>
          <div class="btn-container">
          <%= link_to "Edit", edit_planet_path(@planet), class: "btn-change-border-edit" %>
          <%= link_to "Delete", @planet, data: { confirm: "Are you sure?" }, :method => :delete, class: "btn-change-border-delete" %>
        <% end %>
          </div>
    </div> 
  </section>
</div>
      

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="text-footer">
    <p>This website was coded with<span>  ❤️</span>at Le Wagon by Artsouille Team.
    <br>
    Copyright 2021 Artsouille, Inc. All rights reserved</p>
  </div>

  <div class="links">
    <a href="https://github.com/lewagon" target="blank" rel="noopener noreferrer">
      <i class="fab fa-github fa-2x"></i>
    </a>

    <a href="https://www.facebook.com/lewagonbrussels/" target="blank" rel="noopener noreferrer">
      <i class="fab fa-facebook fa-2x"></i>
    </a>

    <a href="https://www.instagram.com/lewagonbelgium" target="blank" rel="noopener noreferrer">
      <i class="fab fa-instagram fa-2x"></i>
    </a>

    <a href="https://twitter.com/lewagonbrussels" target="blank" rel="noopener noreferrer">
      <i class="fab fa-twitter fa-2x"></i>
    </a>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <i class="fas fa-rocket" style="font-size: 2rem"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Planets", planets_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add a Planet", new_planet_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, width: 50, height: 50, format: "png", gravity: "face", crop: "fill", radius: "max", class: " avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "user-astronaut.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My planets", planets_path(query:'my_planets'), class: "dropdown-item" %>
            <%= link_to "Requests Sent", bookings_path(query: 'sent'), class: "dropdown-item" %>
            <%= link_to "Requests Received", bookings_path(query: 'received'), class: "dropdown-item" %>
            <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-user">
  <h1><%= @user.username %>'s Profile</h1>
    <div class="user-profile">
      <% if @user.avatar.attached? %>
        <%= cl_image_tag(@user.avatar.key, width: 200, height: 200, format: "png", gravity: "face", crop: "fill", radius: "max") %>
      <% end %>
      <% if current_user == @user  %>
      <div class="user-profile-info">

        <div>
          <h2>Your Informations</h2>
          <p>Email: <%= @user.email %></p>
          <p>Password: ****************</p>
        </div>
      <% end %>

      <div>
        <h2>About</h2>
        <p><%= @user.description unless @user.description.nil? %></p>
        <h2>My Planets</h2>
        <% @user.planets.each do |planet| %>
          <p class="user-planet"><%= link_to planet.name, planet_path(planet) %></p>
        <% end %>
      </div>
    </div>
  </div>

  <% if current_user == @user  %>
  <div class="btn-profile">
    <%= link_to "Delete my account", registration_path(current_user), class: "btn btn-outline-warning", data: { confirm: "Are you sure? There is no turning back" }, method: :delete %>
    <%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-outline-primary btn-edit" %>
  </div>
  <% end %>
</div>